version: "3.7"
services:
  node_api:
    container_name: restapi
    image: solmazumut/restapi
    environment:
      - PORT=8080
      - NODE_ENV="development"
      - DB_USER="admin"
      - DATABASE_PASSWORD="123qwe"
      - DB_HOST="0.0.0.0"
      - DB_PORT=5432
      - DB_DATABASE="postgres"
      - DATABASE_URL="testurl"
    ports:
      - 8080:8080
